<script setup lang="ts">
/**
 * AppButton — TASK-079 Phase 4 (2026-08-03, UX audit finding: design
 * system consistency).
 *
 * The audit found src/design-system/components/ held 16 components but
 * NOT the three things every screen actually needs — a Button, a Card and
 * an Input primitive. So every button in the app was raw Tailwind
 * re-declared at the call site, and the padding/radius/size drifted:
 * px-4 py-2 here, px-3 py-1.5 there, rounded-xl on one screen and
 * rounded-lg on the next, with the 44px tap target and the `active:`
 * press state (both added in Phase 3) present on some and missing on
 * others. Nothing enforced any of it, so every new screen re-drifted.
 *
 * This component bakes in what Phases 1-3 established so a caller cannot
 * drift again:
 *   - min-h-[44px] on `md` (Apple HIG minimum — Phase 3 raised ~30 sites
 *     to this). `sm` bottoms out at 40px and no lower.
 *   - `active:scale-95` press feedback — `hover:` never fires on a
 *     touchscreen, which is the only device this portal is used on.
 *   - rounded-xl + font-bold + the brand palette.
 *
 * Colours go through the CSS-var-backed Tailwind classes (bg-brand-600
 * etc., see tailwind.config.js + stores/theme.ts) — NEVER a hardcoded
 * hex, or per-company theming (TASK-055 / ADR-018) silently stops
 * applying to buttons.
 *
 * The `primary` styling is deliberately the de-facto style already in the
 * codebase (`px-4 py-2 rounded-xl bg-brand-600 text-ink-primary font-bold
 * text-sm hover:bg-brand-700`) so adopting it makes nothing visually
 * jump. Its label is now `text-ink-primary` rather than `text-white` —
 * see the TASK-098 note below.
 *
 * ─────────────────────────────────────────────────────────────────────
 * TASK-098 / ADR-023 (2026-08-04) — colours here now come from the
 * surface/ink token layer, not from hardcoded slate/white utilities.
 *
 * ADR-023 §2.3 named `primary: 'bg-brand-600 text-ink-primary'` "the single
 * highest-blast-radius line in the app": the brand ramp is generated by
 * lightness mixing with no contrast maths behind it, so the moment a
 * tenant picks a pale primary this button was white-on-light. The
 * background stays `bg-brand-600` (== `--surface-primary`); only the ink
 * moves to `text-ink-primary`, which the theme store derives by WCAG
 * contrast against that exact background.
 *
 * Renders a <button> by default, or a <RouterLink> when `to` is passed
 * (an in-app link that LOOKS like a button should still be a real link —
 * long-press/open-in-new-tab/middle-click all keep working).
 *
 * Usage:
 *   <AppButton @click="save">บันทึก</AppButton>
 *   <AppButton variant="secondary" size="sm" @click="x">ยกเลิก</AppButton>
 *   <AppButton :loading="creating" block>สร้างคำสั่งซื้อ</AppButton>
 *   <AppButton to="/orders" variant="ghost">ดูทั้งหมด</AppButton>
 */
import { computed } from 'vue'
import { RouterLink } from 'vue-router'

type Variant = 'primary' | 'secondary' | 'danger' | 'ghost'
type Size = 'sm' | 'md'

const props = withDefaults(
  defineProps<{
    variant?: Variant
    size?: Size
    block?: boolean
    loading?: boolean
    disabled?: boolean
    /** Native button type — irrelevant when `to` is set. */
    type?: 'button' | 'submit' | 'reset'
    /** When set, renders a RouterLink instead of a <button>. */
    to?: string | null
  }>(),
  {
    variant: 'primary',
    size: 'md',
    block: false,
    loading: false,
    disabled: false,
    type: 'button',
    to: null,
  },
)

/**
 * Variant → colour. `secondary` is the neutral outlined button the views
 * already used for "ยกเลิก / เสร็จสิ้น"; `ghost` is the borderless text
 * button used for inline links like "ดูทั้งหมด" / "อ่านทั้งหมด".
 *
 * TASK-098 / ADR-023: `secondary` is an outlined button that shares the
 * CARD surface, so it takes card tokens (`bg-surface-card` +
 * `text-ink-card-muted` + `border-line-card`) and its hover tint is the
 * neutral chip surface. `danger` keeps `text-white` deliberately: its
 * background is the FIXED rose-600 ramp, not a themable surface, so
 * white is always the correct ink there and `--ink-primary` (which is
 * derived against the brand primary) would be the wrong token.
 */
const VARIANT_CLASSES: Record<Variant, string> = {
  primary: 'bg-brand-600 text-ink-primary shadow-sm hover:bg-brand-700',
  secondary: 'border border-line-card bg-surface-card text-ink-card-muted hover:bg-surface-chip',
  danger: 'bg-rose-600 text-white shadow-sm hover:bg-rose-700',
  ghost: 'text-brand-600 hover:text-brand-700 hover:bg-brand-50',
}

/**
 * Size → box. Both keep a real tap target: 44px (Apple HIG) on md, and a
 * floor of 40px on sm — the audit's finding was that the HIT AREA was
 * failing, never the legibility, so the type size is what shrinks, not
 * the box.
 */
const SIZE_CLASSES: Record<Size, string> = {
  sm: 'min-h-[40px] px-3 py-1.5 text-xs gap-1',
  md: 'min-h-[44px] px-4 py-2 text-sm gap-1.5',
}

/** A loading button must not be re-tappable — double-submit protection. */
const isInert = computed(() => props.disabled || props.loading)

const classes = computed(() => [
  'inline-flex items-center justify-center rounded-xl font-bold whitespace-nowrap transition-all active:scale-95',
  SIZE_CLASSES[props.size],
  VARIANT_CLASSES[props.variant],
  props.block ? 'w-full' : '',
  isInert.value ? 'opacity-50 cursor-not-allowed pointer-events-none' : '',
])
</script>

<template>
  <!-- Two mutually-exclusive branches (never both) so the RouterLink
       never receives button-only attributes like `type`/`disabled`. -->
  <RouterLink v-if="to" :to="to" :class="classes">
    <slot />
  </RouterLink>
  <button v-else :type="type" :disabled="isInert" :class="classes">
    <!-- Spinner replaces nothing — it sits BEFORE the label so the label
         stays readable and the button keeps (roughly) its width, rather
         than swapping to a "กำลังโหลด..." string that reflows the row. -->
    <svg
      v-if="loading"
      class="animate-spin shrink-0"
      :width="size === 'sm' ? 12 : 14"
      :height="size === 'sm' ? 12 : 14"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" class="opacity-25" />
      <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" stroke-width="4" stroke-linecap="round" />
    </svg>
    <slot />
  </button>
</template>
