<script setup lang="ts">
/**
 * ProductCard — TASK-070 / ADR-020.
 *
 * The single product-card implementation used by BOTH the "Recommended
 * for you" row (row 4) and the main searchable grid on
 * ProductBrowseView.vue, per ADR-020's explicit requirement: "there
 * must be exactly one product-card implementation used in both row 4
 * and the main grid below, not two copies." Extracted verbatim from
 * the pre-TASK-070 ProductBrowseView.vue grid item markup — no visual
 * change, purely a component boundary.
 *
 * TASK-079 Phase 3 (UX audit): the share button was a ~36px box (pt-3
 * beats py-2 in Tailwind's padding order) — under the 44px minimum — and
 * had no `active:` press state, so on a touchscreen tapping it produced
 * no feedback at all. The `:title` on it is left as-is on purpose: the
 * only consumer (ProductBrowseView) already renders the same BR-1 reason
 * as a visible amber banner above the grid, so it is not carrying
 * information that exists nowhere else.
 *
 * BR-1 gate: the "แชร์" button's disabled/locked state is driven
 * entirely by the `hasPassedBasic` prop the parent computes (per
 * TASK-067's own `authStore.user?.id` filter) — this component holds
 * no certification logic of its own, it just renders the prop.
 */
import { RouterLink } from 'vue-router'
import Icon from './Icon.vue'
import AuthenticatedMedia from './AuthenticatedMedia.vue'

export interface ProductCardItem {
  id: number
  name: string
  price_satang: number
  thumbnail_url: string | null
  category?: { id: number; name: string } | null
}

defineProps<{
  product: ProductCardItem
  hasPassedBasic: boolean
  sharing: boolean
}>()

const emit = defineEmits<{ share: [product: ProductCardItem] }>()

function formatBaht(satang: number): string {
  return '฿' + (satang / 100).toLocaleString('th-TH')
}
</script>

<template>
  <!-- TASK-098 / ADR-023 — colours come from the surface/ink token layer.
       The PRICE is the reason this file changed a second time: it was
       `text-brand-700`, and the brand ramp is generated by lightness-mixing
       from primary_hex, so on a black card with a mid-tone primary the 700
       step is a dark version of an already-dim colour and the price sank
       into the background (human-reported 2026-08-04). `text-ink-brand` is
       the same hue walked toward whichever pole this card needs until it
       clears AA — so it still reads as the brand colour. -->
  <!--
       THE CARD IS A LINK TO THE PRODUCT (human request, 2026-08-21:
       "ตัวสินค้าต้องคลิ๊กดูรายละเอียดหน้าใหม่ได้พร้อมปุ่มแชร์").

       Before this the only thing an agent could do to a product was share
       it — the name was clipped to two lines, the price was a number, and
       the description existed only on the page the CUSTOMER would see.
       An agent had to share a link to themselves to read what they were
       selling.

       RouterLink and not a click handler, so the row keeps everything a
       link gives for free: middle-click and long-press open it in a new
       tab, the status bar previews the destination, and the browser treats
       it as navigation rather than as script. -->
  <RouterLink
    :to="{ name: 'product-detail', params: { id: product.id } }"
    class="bg-surface-card/95 border border-line-card rounded-xl overflow-hidden flex flex-col h-full transition hover:border-brand-400 active:scale-[0.99]"
  >
    <AuthenticatedMedia :src="product.thumbnail_url" type="image" class="w-full aspect-square object-cover" />
    <div class="p-3 flex flex-col flex-1">
      <p v-if="product.category" class="text-[11px] text-ink-card-subtle uppercase tracking-wider font-bold mb-0.5">
        {{ product.category.name }}
      </p>
      <p class="text-sm font-bold text-ink-card leading-tight line-clamp-2">{{ product.name }}</p>
      <p class="text-sm font-bold text-ink-brand mt-1">{{ formatBaht(product.price_satang) }}</p>

      <!-- `.stop.prevent` is load-bearing now that the card is a link:
           without it, every share press would ALSO navigate, and the
           modal would open on a page that is already leaving. -->
      <button
        :disabled="!hasPassedBasic || sharing"
        :title="!hasPassedBasic ? 'ต้องผ่านการรับรอง Basic ก่อน (BR-1)' : 'สร้าง/เปิดลิงก์แชร์'"
        class="mt-auto pt-3 min-h-[44px] flex items-center justify-center gap-1.5 text-xs font-bold py-2 rounded-lg transition-all active:scale-95"
        :class="hasPassedBasic
          ? 'bg-surface-primary text-ink-primary hover:opacity-90'
          : 'bg-surface-chip text-ink-chip/50 cursor-not-allowed'"
        @click.stop.prevent="emit('share', product)"
      >
        <Icon name="share" :size="14" />
        {{ sharing ? 'กำลังสร้าง...' : 'แชร์' }}
      </button>
    </div>
  </RouterLink>
</template>
