<script setup lang="ts">
/**
 * ProductCard — TASK-070 / ADR-020.
 *
 * The single product-card implementation used by BOTH the "Recommended
 * for you" row (row 4) and the main searchable grid on
 * ProductBrowseView.vue, per ADR-020's explicit requirement: "there
 * must be exactly one product-card implementation used in both row 4
 * and the main grid below, not two copies." Extracted verbatim from
 * the pre-TASK-070 ProductBrowseView.vue grid item markup — no visual
 * change, purely a component boundary.
 *
 * TASK-079 Phase 3 (UX audit): the share button was a ~36px box (pt-3
 * beats py-2 in Tailwind's padding order) — under the 44px minimum — and
 * had no `active:` press state, so on a touchscreen tapping it produced
 * no feedback at all. The `:title` on it is left as-is on purpose: the
 * only consumer (ProductBrowseView) already renders the same BR-1 reason
 * as a visible amber banner above the grid, so it is not carrying
 * information that exists nowhere else.
 *
 * BR-1 gate: the "แชร์" button's disabled/locked state is driven
 * entirely by the `hasPassedBasic` prop the parent computes (per
 * TASK-067's own `authStore.user?.id` filter) — this component holds
 * no certification logic of its own, it just renders the prop.
 */
import { RouterLink } from 'vue-router'
import Icon from './Icon.vue'
import AuthenticatedMedia from './AuthenticatedMedia.vue'

export interface ProductCardItem {
  id: number
  name: string
  /**
   * The ROW's own price. For a platform-owned product (ADR-040) that is the
   * CENTRAL price, which no company necessarily charges — so this is not the
   * number to put in front of an agent. See `effective_price_satang`.
   */
  price_satang: number
  /**
   * TASK-257 / ADR-040 — what THIS agent's company actually charges: its own
   * price if it set one, the central price if not, and an active promotion
   * above either. Resolved server-side (ProductPricingService) and sent by
   * ProductResource on every /products read.
   *
   * Optional, and that is deliberate rather than defensive: every caller
   * today sends it, and a future one that does not should quote a stale
   * number a human once typed rather than render NaN at a customer.
   */
  effective_price_satang?: number | null
  thumbnail_url: string | null
  /** 2026-09-09 — the inline blur-up copy; see AuthenticatedMedia. */
  thumbnail_placeholder?: string | null
  category?: { id: number; name: string } | null
}

defineProps<{
  product: ProductCardItem
  hasPassedBasic: boolean
  sharing: boolean
  /** 2026-09-14 — the second button's own spinner; see the template. */
  buying?: boolean
}>()

const emit = defineEmits<{
  share: [product: ProductCardItem]
  buy: [product: ProductCardItem]
}>()

function formatBaht(satang: number): string {
  return '฿' + (satang / 100).toLocaleString('th-TH')
}

/**
 * The one number this card is allowed to show.
 *
 * `??`, never `||`: a free onboarding item is a real price a Super Admin
 * typed, and `||` would read 0 as "missing" and quote the central price
 * instead — silently, at the one moment the difference is largest.
 */
function priceOf(product: ProductCardItem): number {
  return product.effective_price_satang ?? product.price_satang
}
</script>

<template>
  <!-- TASK-098 / ADR-023 — colours come from the surface/ink token layer.
       The PRICE is the reason this file changed a second time: it was
       `text-brand-700`, and the brand ramp is generated by lightness-mixing
       from primary_hex, so on a black card with a mid-tone primary the 700
       step is a dark version of an already-dim colour and the price sank
       into the background (human-reported 2026-08-04). `text-ink-brand` is
       the same hue walked toward whichever pole this card needs until it
       clears AA — so it still reads as the brand colour. -->
  <!--
       THE CARD IS A LINK TO THE PRODUCT (human request, 2026-08-21:
       "ตัวสินค้าต้องคลิ๊กดูรายละเอียดหน้าใหม่ได้พร้อมปุ่มแชร์").

       Before this the only thing an agent could do to a product was share
       it — the name was clipped to two lines, the price was a number, and
       the description existed only on the page the CUSTOMER would see.
       An agent had to share a link to themselves to read what they were
       selling.

       RouterLink and not a click handler, so the row keeps everything a
       link gives for free: middle-click and long-press open it in a new
       tab, the status bar previews the destination, and the browser treats
       it as navigation rather than as script. -->
  <RouterLink
    :to="{ name: 'product-detail', params: { id: product.id } }"
    class="bg-surface-card/95 border border-line-card rounded-xl overflow-hidden flex flex-col h-full transition hover:border-brand-400 active:scale-[0.99]"
  >
    <AuthenticatedMedia
      :src="product.thumbnail_url"
      :placeholder="product.thumbnail_placeholder"
      type="image"
      class="w-full aspect-square object-cover"
    />
    <div class="p-3 flex flex-col flex-1">
      <p v-if="product.category" class="text-[11px] text-ink-card-subtle uppercase tracking-wider font-bold mb-0.5">
        {{ product.category.name }}
      </p>
      <p class="text-sm font-bold text-ink-card leading-tight line-clamp-2">{{ product.name }}</p>
      <!--
        TASK-257 / ADR-040 — the price THIS agent's company charges, not the
        platform's central one. The two are the same number for every
        company-owned product, and diverge the moment a product is promoted
        into the shared catalog — at which point this grid would quote one
        figure and the order take another, in front of the customer the agent
        has to explain it to.
      -->
      <p class="text-sm font-bold text-ink-brand mt-1">{{ formatBaht(priceOf(product)) }}</p>

      <!--
        TWO ACTIONS ON ONE LINK (human, 2026-09-14: "ให้เพิ่มปุ่มสั่งซื้อได้เลย
        เอาไว้คู่กับปุ่มแชร์").

        แชร์ hands the link to the customer; สั่งซื้อ opens the page that link
        leads to, so the agent can take the order with the customer in front of
        them. Both mint the SAME idempotent share link — see useProductShare —
        which is also why both carry the same BR-1 lock: the server refuses to
        mint for an uncertified agent, so an unlocked สั่งซื้อ would be a button
        whose only outcome is an error.

        `.stop.prevent` on both is load-bearing, because the card is a
        RouterLink: without it every press would ALSO navigate to the detail
        page, and the sheet would open on a page that is already leaving.

        Side by side, `flex-1 min-w-0` with `truncate` labels: the grid is two
        columns on a phone, so a card is ~160px wide and neither label may be
        what decides the card's width.
      -->
      <div class="mt-auto pt-3 flex items-stretch gap-1.5">
        <button
          :disabled="!hasPassedBasic || sharing || buying"
          :title="!hasPassedBasic ? 'ต้องผ่านการรับรอง Basic ก่อน (BR-1)' : 'สร้าง/เปิดลิงก์แชร์'"
          class="flex-1 min-w-0 min-h-[44px] flex items-center justify-center gap-1 text-[11px] font-bold py-2 px-1.5 rounded-lg transition-all active:scale-95"
          :class="hasPassedBasic
            ? 'bg-surface-chip text-ink-card border border-line-card hover:opacity-90'
            : 'bg-surface-chip text-ink-chip/50 cursor-not-allowed'"
          data-test="product-share-button"
          @click.stop.prevent="emit('share', product)"
        >
          <Icon name="share" :size="13" class="shrink-0" />
          <span class="truncate">{{ sharing ? 'กำลังสร้าง...' : 'แชร์' }}</span>
        </button>

        <!-- The filled one, because this is the action that ends in money.
             แชร์ gives up the solid fill it used to have and keeps the same
             position; it is still the more common press, but it is a step
             toward a sale rather than the sale. -->
        <button
          :disabled="!hasPassedBasic || sharing || buying"
          :title="!hasPassedBasic ? 'ต้องผ่านการรับรอง Basic ก่อน (BR-1)' : 'เปิดหน้าสั่งซื้อของสินค้านี้'"
          class="flex-1 min-w-0 min-h-[44px] flex items-center justify-center gap-1 text-[11px] font-bold py-2 px-1.5 rounded-lg transition-all active:scale-95"
          :class="hasPassedBasic
            ? 'bg-surface-primary text-ink-primary hover:opacity-90'
            : 'bg-surface-chip text-ink-chip/50 cursor-not-allowed'"
          data-test="product-buy-button"
          @click.stop.prevent="emit('buy', product)"
        >
          <Icon name="cart" :size="13" class="shrink-0" />
          <span class="truncate">{{ buying ? 'กำลังเปิด...' : 'สั่งซื้อ' }}</span>
        </button>
      </div>
    </div>
  </RouterLink>
</template>
