// Fixed, hardcoded list of Thailand's 77 provinces (76 provinces +
// Bangkok as a special administrative area) — TASK-014's Design notes:
// this is a geographic fact, not an unfinalized business value (BR-7
// doesn't apply), so it's a plain constant, not admin-editable config.
// Mirrors backend/app/Support/ThailandProvinces.php exactly — keep both
// in sync if this list ever changes (ADR-003: no shared package between
// frontend/frontend-admin/backend).
export const THAILAND_PROVINCES: readonly string[] = [
  'กรุงเทพมหานคร',
  'อำนาจเจริญ',
  'อ่างทอง',
  'บึงกาฬ',
  'บุรีรัมย์',
  'ฉะเชิงเทรา',
  'ชัยนาท',
  'ชัยภูมิ',
  'จันทบุรี',
  'เชียงใหม่',
  'เชียงราย',
  'ชลบุรี',
  'ชุมพร',
  'กาฬสินธุ์',
  'กำแพงเพชร',
  'กาญจนบุรี',
  'ขอนแก่น',
  'กระบี่',
  'ลำปาง',
  'ลำพูน',
  'เลย',
  'ลพบุรี',
  'แม่ฮ่องสอน',
  'มหาสารคาม',
  'มุกดาหาร',
  'นครนายก',
  'นครปฐม',
  'นครพนม',
  'นครราชสีมา',
  'นครสวรรค์',
  'นครศรีธรรมราช',
  'น่าน',
  'นราธิวาส',
  'หนองบัวลำภู',
  'หนองคาย',
  'นนทบุรี',
  'ปทุมธานี',
  'ปัตตานี',
  'พังงา',
  'พัทลุง',
  'พะเยา',
  'เพชรบูรณ์',
  'เพชรบุรี',
  'พิจิตร',
  'พิษณุโลก',
  'พระนครศรีอยุธยา',
  'แพร่',
  'ภูเก็ต',
  'ปราจีนบุรี',
  'ประจวบคีรีขันธ์',
  'ระนอง',
  'ราชบุรี',
  'ระยอง',
  'ร้อยเอ็ด',
  'สระแก้ว',
  'สกลนคร',
  'สมุทรปราการ',
  'สมุทรสาคร',
  'สมุทรสงคราม',
  'สระบุรี',
  'สตูล',
  'สิงห์บุรี',
  'ศรีสะเกษ',
  'สงขลา',
  'สุโขทัย',
  'สุพรรณบุรี',
  'สุราษฎร์ธานี',
  'สุรินทร์',
  'ตาก',
  'ตรัง',
  'ตราด',
  'อุบลราชธานี',
  'อุดรธานี',
  'อุทัยธานี',
  'อุตรดิตถ์',
  'ยะลา',
  'ยโสธร',
]
