<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// TASK-053 / ADR-016 Phase 1 — the platform's first real notification
// store (the bell was a stub). One row per notification to one user;
// generated by NotificationService on events (announcement targeting the
// agent, follow-up due, exam pass/fail, commission paid, approval change,
// etc). Tenant-scoped via company_id (§5). `link` is an optional
// route-name/path the frontend can navigate to; `data` is optional
// structured context. read_at null = unread.
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->string('type'); // App\Enums\NotificationType
            $table->string('title');
            $table->text('body')->nullable();
            $table->string('link')->nullable(); // route name or path the frontend can open
            $table->json('data')->nullable();
            $table->timestamp('read_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'read_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('notifications');
    }
};
